include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_final_parameters: true
    prefer_single_quotes: true
    use_string_buffers: true
