name: blank_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.0.1
  intl: any
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/config/local.json
    - path: assets/config/dev.json
      flavors:
        - dev
