name: blank_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_performance: ^0.10.1+10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/config/local.json
    - path: assets/config/dev.json
      flavors:
        - dev
