name: blank_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.0
  go_router: ^14.2.8
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/config/local.json
    - path: assets/config/dev.json
      flavors:
        - dev
