name: blank_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  firebase_performance: ^0.10.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.7.2
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/config/local.json
    - path: assets/config/dev.json
      flavors:
        - dev
